// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProfileService.Repository;

#nullable disable

namespace ProfileService.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220521163000_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProfileService.Model.Connection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Profile1Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Profile2Id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Profile1Id");

                    b.HasIndex("Profile2Id");

                    b.ToTable("Connections");
                });

            modelBuilder.Entity("ProfileService.Model.ConnectionRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequestedProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequestingProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("RequestedProfileId");

                    b.HasIndex("RequestingProfileId");

                    b.ToTable("ConnectionRequests");
                });

            modelBuilder.Entity("ProfileService.Model.Education", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("School")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("Education");
                });

            modelBuilder.Entity("ProfileService.Model.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Public")
                        .HasColumnType("boolean");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("ProfileService.Model.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("ProfileService.Model.WorkExperience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("WorkExperiences");
                });

            modelBuilder.Entity("ProfileService.Model.Connection", b =>
                {
                    b.HasOne("ProfileService.Model.Profile", "Profile1")
                        .WithMany()
                        .HasForeignKey("Profile1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProfileService.Model.Profile", "Profile2")
                        .WithMany()
                        .HasForeignKey("Profile2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile1");

                    b.Navigation("Profile2");
                });

            modelBuilder.Entity("ProfileService.Model.ConnectionRequest", b =>
                {
                    b.HasOne("ProfileService.Model.Profile", "RequestedProfile")
                        .WithMany()
                        .HasForeignKey("RequestedProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProfileService.Model.Profile", "RequestingProfile")
                        .WithMany()
                        .HasForeignKey("RequestingProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestedProfile");

                    b.Navigation("RequestingProfile");
                });

            modelBuilder.Entity("ProfileService.Model.Education", b =>
                {
                    b.HasOne("ProfileService.Model.Profile", null)
                        .WithMany("Education")
                        .HasForeignKey("ProfileId");
                });

            modelBuilder.Entity("ProfileService.Model.Profile", b =>
                {
                    b.HasOne("ProfileService.Model.Profile", null)
                        .WithMany("Blocked")
                        .HasForeignKey("ProfileId");
                });

            modelBuilder.Entity("ProfileService.Model.Skill", b =>
                {
                    b.HasOne("ProfileService.Model.Profile", null)
                        .WithMany("Skills")
                        .HasForeignKey("ProfileId");
                });

            modelBuilder.Entity("ProfileService.Model.WorkExperience", b =>
                {
                    b.HasOne("ProfileService.Model.Profile", null)
                        .WithMany("WorkExperiences")
                        .HasForeignKey("ProfileId");
                });

            modelBuilder.Entity("ProfileService.Model.Profile", b =>
                {
                    b.Navigation("Blocked");

                    b.Navigation("Education");

                    b.Navigation("Skills");

                    b.Navigation("WorkExperiences");
                });
#pragma warning restore 612, 618
        }
    }
}
