name: ASP.NET-CI

on:
  pull_request:
    branches: [develop, main]
  push:
    branches: [develop, main]

env:
  PROJ_DIR: ./ProfileService
  PACKAGE_DIR: ${{ format('{0}/{0}', 'ProfileService') }}
  PACKAGE_PATH: ${{ format('{0}/{0}/bin/Release/*.nupkg', 'ProfileService') }}
  DOCKERHUB_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/profile-service


jobs:
  ci-pipe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Lint commit messages
        uses: wagoid/commitlint-github-action@v4

      - name: Cache Dependencies NuGet
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/package-lock.json')}}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Add GPR
        run: dotnet nuget add source --username ekipa --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Vegari-1/index.json"
      - name: Install Dependencies
        working-directory: ${{ env.PROJ_DIR }}
        run: dotnet restore
      - name: Build App
        working-directory: ${{ env.PROJ_DIR }}
        run: dotnet build --configuration Release --no-restore
      - name: Run Tests
        working-directory: ${{ env.PROJ_DIR }}
        run: dotnet test --no-restore --verbosity normal
      
      - name: Create a Release
        id: version
        if: github.event_name == 'push'
        run: |
          npm install semantic-release
          npm install semantic-release-export-data
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Package
        if: github.event_name == 'push'
        working-directory: ${{ env.PACKAGE_DIR }}
        run: dotnet pack --configuration Release --no-build /p:Version=${{ steps.version.outputs.new-release-version }}
      
      - name: Publish the package to GPR
        if: github.event_name == 'push'
        run: |
          dotnet nuget add source --username ekipa --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Vegari-1/index.json"
          dotnet nuget push ${{ env.PACKAGE_PATH }} --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"

      - name: Set up Docker Buildx
        if: github.event_name == 'push'
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        if: github.event_name == 'push'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build image and push to Docker Hub
        if: github.event_name == 'push'
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.PROJ_DIR }}
          tags: ${{ env.DOCKERHUB_REPO }}:latest, ${{ env.DOCKERHUB_REPO }}:${{ steps.version.outputs.new-release-version }}
          push: true
          cache-from: type=registry,ref=${{ env.DOCKERHUB_REPO }}:buildcache
          cache-to: type=registry,ref=${{ env.DOCKERHUB_REPO }}:buildcache,mode=max
